### ISSUE TITLE
dynamic labeling for routing

### ISSUE THREAD

**Issue by ansis** [mapbox/DEPRECATED-mapbox-gl#1]
Dynamically adapting what labels are shown and how they look based on a route.

For example:
- making roads used by the route have bigger labels
- deemphasizing roads that don't cross the route
- placing labels for intersecting roads close to the intersection
- adding pois near turns to make them easier to identify

I don't think this would be entirely implemented within core mapbox gl but we would need to implement some apis to make this possible.

**Comment by andreasviglakis** [comment]
This would be amazing!

**Comment by lucaswoj** [comment]
migrated to https://github.com/mapbox/mapbox-gl-js/issues/3992
