### ISSUE TITLE
Add has / !has filter operators

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/DEPRECATED-mapbox-gl#10]
fixes https://github.com/mapbox/mapbox-gl-style-spec/issues/364

ref https://github.com/mapbox/vector-tile-spec/issues/62
ref  https://github.com/mapbox/mapbox-gl-js/issues/2162
- [ ] update mapbox-gl-style-spec (PR at https://github.com/mapbox/mapbox-gl-style-spec/pull/421) 
- [ ] update feature-filter (PR at https://github.com/mapbox/feature-filter/pull/15)
- [ ] update mapbox-gl-js
- [ ] update mapbox-gl-native

**Comment by jfirebaugh** [comment]
Additional order-dependent steps include supporting the new filters in the server side validations and in Mapbox Studio.
