### ISSUE TITLE
zooming and panning raster tileset causes kaleidescope effect

### ISSUE THREAD

**Issue by jamescartifact** [mapbox/DEPRECATED-mapbox-gl#11]
Raster tileset causing general sluggish performance issues in Studio.

Appears OK in browser when static, but zooming and panning causes a flashing kaleidoscope effect with tile repetition and the disappearance of vector overlays.

https://api.mapbox.com/styles/v1/cartifact/cilokgkab001ea7ltzhoohn5c.html?title=true&access_token=pk.eyJ1IjoiY2FydGlmYWN0IiwiYSI6IjliMDg0NzQ1ODZiMTM0YTAzODQ5Y2ZhNzVlMGEyOTI5In0.ZGKQW8lwsLIAClTVM2jMJQ#14.31493542571246/37.84708589407768/-122.53484191538575/0

![screen shot 2016-03-11 at 7 26 01 pm copy](https://cloud.githubusercontent.com/assets/17776358/13720518/e7a3da9c-e7bf-11e5-85eb-6cad580382c0.jpg)
![screen shot 2016-03-11 at 7 25 48 pm copy](https://cloud.githubusercontent.com/assets/17776358/13720520/e7ad9820-e7bf-11e5-8eb2-703f660826f8.jpg)
![screen shot 2016-03-11 at 7 25 34 pm copy](https://cloud.githubusercontent.com/assets/17776358/13720519/e7a5cc3a-e7bf-11e5-9a9e-6ebaf043526f.jpg)

**Comment by ansis** [comment]
fixed here: https://github.com/mapbox/mapbox-gl-js/issues/2304
