### ISSUE TITLE
Standardize background color

### ISSUE THREAD

**Issue by kkaefer** [mapbox/DEPRECATED-mapbox-gl#12]
When rendering a transparent background image in the browser, we're typically getting a white background, but on native, we're typically getting a black background. We should standardize the background color of Mapbox GL and never let any sort of background of the embedding application shine through.

**Comment by jfirebaugh** [comment]
That would conflict with https://github.com/mapbox/mapbox-gl-native/issues/3038 / https://github.com/mapbox/mapbox-gl-native/issues/3040.

I think we should take the opposite approach: rendering no layers, or only transparent layers, should _always_ let the background of the embedding application shine through.

**Comment by kkaefer** [comment]
Thanks for flagging.
