### ISSUE TITLE
Allow style functions based upon computed properties

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/DEPRECATED-mapbox-gl#15]
``` js
{
  property: ['/', 'population', 'area'],
  stops: [[0, 'red'], [100, 'green']]
}
```

You can currently style features based on a single property and / or zoom. There are cases in which styling a feature based on a mathematical expression may be desirable, for example drawing a choropleth map of a ratio. 
- [ ] extend `feature-filter` to accept mathematical operators
- [ ] amend the style spec
- [ ] implement the feature in GL JS
- [ ] implement the feature in GL Native

**Comment by lucaswoj** [comment]
Perhaps this syntax could be extended to allow "joining" data with another source:

```
{
  property: ['getJSON', 'data.json', 'id'],
  stops: [[0, 'red'], [100, 'green']]
}
```

**Comment by jfirebaugh** [comment]
Let's keep the discussion in https://github.com/mapbox/mapbox-gl-style-spec/issues/47.
