### ISSUE TITLE
Convert strings in Mathematical comparison filters (ie: >, >=, <, <=)

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/DEPRECATED-mapbox-gl#19]
In working on Studio one of the harder concepts to communicate is the difference between a `string` and a `number` in the stylespec/data. This has become more difficult as we've started to let users create their own datasources in the UI. In every user testing session we've had so far users have found themselves confused about why  `8 < 9` (which is really `8 < '9'`) results in a false filter. We've tried to find good ways to explain what is going on with little positive result.

I know that simply converting strings to numbers is also problematic but if the operation is inherently mathematical do these problems go away?

/cc @mapbox/appbox @lucaswoj @jfirebaugh

**Comment by samanpwbb** [comment]
Mapbox Studio currently has to force users to pick between strings and numbers when creating and using data. It's the number one biggest stumbling block during user testing: Users do not expect to have to do this, and after many iterations we still struggle to find good ways to communicate type to users. 

Letting greater than and less than filters handle strings that looks like numbers as numbers would save users hundreds of hours and probably even more tears.

**Comment by samanpwbb** [comment]
Lets make Studio smarter about picking type for user.
