### ISSUE TITLE
Creating duotones from raster imagery

### ISSUE THREAD

**Issue by tristen** [mapbox/DEPRECATED-mapbox-gl#23]
From this style panel:

![screen shot 2016-07-29 at 3 55 07 pm](https://cloud.githubusercontent.com/assets/61150/17261651/eb02effe-55a4-11e6-819b-d6ae6bf5cef6.png)

I'd love to be able to assign a color to the whites and a color to the blacks to create a duotone effect like this:

![1--ncslwhahmwjebvp8hks0q](https://cloud.githubusercontent.com/assets/61150/17261677/0e09f1b4-55a5-11e6-9af1-b4fb820e645c.jpeg)

---

I tried a combination of dropping saturation, adjusting brightness, and spinning the hue based on the current raster filtering operations but I'm unable to achieve that exact effect. cc @kkaefer

**Comment by lucaswoj** [comment]
Merging with https://github.com/mapbox/mapbox-gl-js/issues/3889
