### ISSUE TITLE
Adding custom cluster aggregation support

### ISSUE THREAD

**Issue by redbmk** [mapbox/DEPRECATED-mapbox-gl#26]
I've been working on getting support for custom aggregations within clusters. There's been some discussion at mapbox/mapboxgl-js#2412 about adding support for cluster properties.

I'm not sure the best way to go about getting a change implemented, but I'm willing to work on the code, and I have a rough draft I'd like to get reviewed. Could somebody please walk me through the process of getting the code reviewed and merged? It involves changes to at least three projects - [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js), [mapbox-gl-style-spec](https://github.com/mapbox/mapbox-gl-style-spec), and [supercluster](https://github.com/mapbox/supercluster).

I still need to write tests and make changes to the spec. Also I figure it will need to be tested and code reviewed for style, browser support, error checking, safety/security, speed, etc. Regardless, here's what I have so far:
- [supercluster changes](https://github.com/mapbox/supercluster/compare/master...redbmk:4d54aeb)
- [mapbox-gl-js changes](https://github.com/mapbox/mapbox-gl-js/compare/master...redbmk:0a33ec7)

Then in your mapbox style you could provide an option like this:

```
clusterAggregates: {
  property1: 'sum',
  property2: 'min',
  property3: 'min',
  property4: 'max'
}
```

I'm also not sure how much error/type checking should be involved (Also is it better to discuss this here or in the mapbox-gl-js issue referenced above?). Would we expect users to have proper numbers in all the properties for all the points they want aggregated, or should we do things like `Number(num) || 0)` when summing and something like `Math.max(Number(num1) || -Infinity, Number(num2) || -Infinity)`? The code as it is now just assumes you're providing legit numbers. Technically the `sum` option would concatenate strings.

**Comment by redbmk** [comment]
Hmm, I don't actually see any tests currently involving clusters. I'm not really sure where to get started. There's not even a test file for the new `geojson_worker_source.js`.

**Comment by redbmk** [comment]
Made some changes to the spec as well:
- [mapbox-gl-style-spec changes](https://github.com/mapbox/mapbox-gl-style-spec/compare/mb-pages...redbmk:1dc53ae)

**Comment by lucaswoj** [comment]
Thanks @redbmk! Does that syntax support calculating both the `sum` and the `min` of a particular key? What do you think about something like this?

``` js
clusterAggregates: {
  priceSum: ['sum', 'price'],
  priceMin: ['min', 'price'],
  sizeMax: ['max', 'size']
}
```

**Comment by redbmk** [comment]
That's a good point, it doesn't. I like that syntax, although I wonder for
compatibility (and speed?) if using an array of arrays might be better.
Something like

```
clusterAggregates: [
  [ 'priceSum', 'sum', 'price' ],
  [ 'priceMin', 'min', 'price' ],
  [ 'sizeMax', 'max', 'size' ],
]
```

I like your syntax better. What's mapbox's browser support like? I'd have
to look into it but I'm not sure if an old IE would support `for (var
property in hash)` which would sure look nicer than a classic for loop.
We'd also have to do some benchmarking to see what's faster.

**Comment by redbmk** [comment]
Supposedly IE6 supports `for...in`, so that shouldn't be a problem.

Regardless, this is getting a little tricky. The supercluster code I have now gives you the properties from the point and the neighbor, and expects you to return a new hash that gets set on the new cluster. That new set of properties will get passed in on the next call in place of the point's properties.

If geojson_worker_source changes the name from price to priceSum, it won't be clear which property to accumulate with. I suppose supercluster could also pass in some meta information like whether it's a cluster or not, or maybe even give the numPoints (might as well give the x/y coordinates as well).

Any ideas? I'll get another rough draft together here soon.

**Comment by lucaswoj** [comment]
We aim to support all browsers that support WebGL. This includes IE11+ (not IE6). You will find many `for...in` loops in our codebase. 

@mourner Can you comment on the feature, syntax, and architecture proposal?

**Comment by mourner** [comment]
Supercluster already indicates whether a cluster or not with `cluster: true`, so I think we can use that to figure out what properties to aggregate (either `price` or `priceSum`). And the style would then treat clusters and single points differently, either displaying `priceSum` or `price`.

Regarding performance — I don't think syntax matters here because we can normalize it to whatever is fastest as an implementation detail in supercluster. @lucaswoj's proposal probably looks cleaner.

**Comment by redbmk** [comment]
OK, I reworked them a bit to allow for the new syntax, which changes the supercluster arguments a bit - but since they never went live we don't really have to worry about backwards compatibility.

Now supercluster passes in `{ numPoints, properties }` for both the current point and the neighbor. That lets mapbox know whether it's a cluster or a single point so it can decide whether to use the `srcProperty` or the `destProperty` for aggregating. I also added some sanity checks to make sure we're working with numbers.

Is there a good sample project to test this out on for speed and functionality? It took a bit of weirdness to get everything compiled to test it in my current project, and it actually seems like there's a bug in the master branch that was causing my project to throw some errors. I tested the old code with an older version (v0.21.0) and it worked like a charm, but I also don't have a ton of data points.

Here are the latest changes:
- [supercluster](https://github.com/mapbox/supercluster/compare/master...redbmk:cluster-agg-hash-array)
- [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js/compare/master...redbmk:cluster-agg-hash-array)
- [mapbox-gl-style-spec](https://github.com/mapbox/mapbox-gl-style-spec/compare/mb-pages...redbmk:cluster-agg-hash-array)

About the style spec, is there a better way to describe the type of the object? This is what I have now, but I feel like there's a more proper way to spec it out:

```
"clusterAggregates": {
  "type": "*", 
  "default": null,
  "doc": "Properties to aggregate in the form of `{ destProperty: [ aggType, srcProperty ] }`. Valid `aggType`s are 'min', 'max', or 'sum'. For example, `{ property1Sum: [ 'sum', 'property1' ], property2: [ 'min', 'property2' ] }`"
}
```

**Comment by redbmk** [comment]
@mourner, I'm on a pretty slow internet connection at the moment - just saw your comment. It looks like `cluster: true` doesn't get applied until the very end, when it's converting it to JSON, but at that point we've already gone through all the points and converted them to clusters.

I just pushed some new changes that implement @lucaswoj's suggestion, but uses `numPoints` instead of `cluster: true`. I also passed in `extend({}, b.properties)` instead of simply `b.properties` to try to avoid custom aggregate functions from modifying a point or cluster's properties directly, but maybe that's overkill.

**Comment by redbmk** [comment]
Alright, turns out I had some bugs, but I have a working test now. I'm using the earthquakes cluster example from the docs but modified to use clusterAggregates (just min and max since they seemed to make sense in this situation).

I also added a couple aggregates, so the final result now is:
- `sum`: adds numbers
- `min`: minimum of numbers
- `max`: maximum of numbers
- `min_string`: minimum string (aaron aaronson)
- `max_string`: maximum string (zzron zzronson)
- `and`: boolean and
- `or`: boolean or

https://redbmk.github.io/mapbox-gl-js/

I'm really unsure about how to document the style-spec though. I just left it as is for now, but I feel like there's got to be some way to say something like `"type": "cluster_aggregate"` and then define what a `cluster_aggregate` is. I'm just not really familiar with it. Is there documentation on the style spec somewhere?

**Comment by mourner** [comment]
@redbmk I reviewed your changes — I think the concept and the implementation are great. My only concern is performance — let's make sure we avoid any new allocations if possible  (like the `extend({}, properties)` case mentioned above), and also do benchmarks on massive datasets to compare `master` vs `updated + no accumulator function` vs `updated + aggregating`.

**Comment by redbmk** [comment]
Sorry it took so long to get to this. I have a feeling there's a _much_ easier way to do the benchmarking. I probably should have asked first...

I took out the `extend`s and pulled in the latest mapbox changes. Then I updated the test page (https://redbmk.github.io/mapbox-gl-js) to generate some random points that pretend to be earthquakes. You can pick how many to generate, and then whether to run it with the original version, the updated version, or updated w/ aggregates. Then it shows you how many ms it took from `addSource` to the source's `load` event.

It seems kind of inconsistent. Sometimes the original is faster and sometimes the aggregates are faster. I was testing mostly with 500k points (my laptop couldn't handle much more than that) and it usually took anywhere from 8 to 11 seconds.

**Comment by johnlaur** [comment]
Hello; I have been following many of the discussions on this over the past few weeks since the lack of any kind of underlying data roll-up in the clustering became an issue for a use case that we have.

I noticed @mourner is being very diligent in wanting to further solutions which retain O(n) performance on large datasets. I think that is a very noble goal; however please do keep in mind there are many use cases for clustering which do not necessarily have to work for millions of data points and for which aggregation of references to the underlying points or other statistical aggregation functions that are more complex (median, mode, etc.) may have adequate performance and memory requirements in smaller datasets.

For instance, a potential use case for is to use clustering to display a moderate number of data points in  a mobile app in order to declutter and disambiguate touch targets. In this case, we may be operating on a much smaller number of data points. A tap on a cluster might then display a table of values taken form the properties of each data point in the cluster.

I am curious if an aggregation solution for underlying points such as a reference tree walker or for with slower statistical functions would be accepted into mapbox and supercluster provided it had adequate documentation about the performance limits in browser. Even it it has poor in-browser performance on large data, it could still be useful to pregenerate clustered data server-side.

**Comment by mourner** [comment]
Thanks for input everyone! I'll likely start pushing to get this into GL JS next week.

**Comment by cyrilchapon** [comment]
Hey =) Sounds promising. Any status on this ?

**Comment by redbmk** [comment]
@mourner @lucaswoj 

Is there anything I can do to help move this along? Maybe I could look into writing some tests (mind you I'm not really sure how to go about performance tests for this...) or move my code snippets into PRs?

I'd love to improve the spec - is there any documentation on the format for that? Right now it just accepts an arbitrary object, but it seems like it should be able to enforce certain keys and value types.

**Comment by lucaswoj** [comment]
Thank you for the offer to help @redbmk! The next steps for this project are

 - further discussion & consensus on https://github.com/mapbox/mapbox-gl-function/issues/28 (becase we'll want to standardize our syntax between this & that)
 - writing code

**Comment by redbmk** [comment]
Interesting. If we support arbitrary expressions then we wouldn't need to have any preset aggregate functions like "sum" or "max". It would make some simple aggregates a bit more complicated, but adds a lot of flexibility. I'd imagine we would want to be able to define an initialization value as well as a function so we could do something like this (going back to an earlier example):

```
clusterAggregates: {
  priceSum: [ 0, "priceSum + sum" ],
  priceMin: [ Infinity, "priceMin < price ? priceMin : price" ],
  sizeMax: [ -Infinity, "sizeMax > size ? sizeMax : size" ]
}
```

The code used to evaluate the expression could be shared between this and mapbox/mapbox-gl-function#28. The main difference would be to initialize the aggregate variables first, then pass a function to supercluster. I think the supercluster changes I already have would still work with this in mind.

**Comment by redbmk** [comment]
Thinking about this a bit more - not only the new aggregate variable would have to be initialized, but there would be issues if the other variable being used weren't. So, maybe it would be better to leave it up to the expression definition to handle it, but that would make something seemingly simple like "max" quite complicated. For example:

`Math.max(Number(priceMax) === priceMax ? priceMax : Infinity, Number(price) === price ? price : Infinity)`

Maybe there could be some predefined aggregates - so you could simply say `max` or `min` like suggested previously - but then also allow for custom ones somehow. Maybe by prefacing or wrapping something with a keyword, like "eval" (e.g. `eval(allNames + ',' + name)` or `eval: hasDoctor || doctor`).

**Comment by lucaswoj** [comment]
merging into https://github.com/mapbox/mapbox-gl-js/issues/2412
