### ISSUE TITLE
Add support for rendering characters from unicode supplementary planes

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/DEPRECATED-mapbox-gl#29]
We currently only support rendering characters from the [Basic Multilingual Plane](https://en.wikipedia.org/wiki/Plane_%28Unicode%29#Basic_Multilingual_Plane). We may need to support supplementary planes as we expand into markets that use non-Latin alphabets. 

> https://en.wikipedia.org/wiki/CJK_Unified_Ideographs#CJK_Unified_Ideographs_Extension_E notes that 98 of those characters come from “Chinese Academy of Surveying and Mapping ideographs”, so they probably will be cropping up in OSM eventually. -- @1ec5

**Comment by 1ec5** [comment]
I’m satisfied that the CJK Unified Ideographs Extension E characters will take awhile to make their way into OpenStreetMap, given that the block was only introduced to Unicode last year. However, note that the same work that goes into CJK E would also enable (colorless) emoji. Hopefully that’ll give this issue a bit more traction. 😉

**Comment by 1ec5** [comment]
My mistake: CJK E isn’t the only CJK block that’s in the Supplementary Ideographic Plane; CJK Unified Ideographs Extension B–D are also up there. Besides historical and Vietnamese characters, CJK B includes 1,702 characters from the [Hong Kong Supplementary Character Set](https://en.wikipedia.org/wiki/Hong_Kong_Supplementary_Character_Set), which apparently includes a lot of Cantonese characters used in official Hong Kong place names.

**Comment by 1ec5** [comment]
As of Unicode 9.0, the following astral-plane blocks allow ideographic breaking:
- Meroitic Hieroglyphs
- Egyptian Hieroglyphs
- Anatolian Hieroglyphs
- Ideographic Symbols and Punctuation
- Tangut
- Tangut Components
- Kana Supplement
- Tai Xuan Jing Symbols
- Counting Rod Numerals
- Mahjong Tiles
- Domino Tiles
- Playing Cards
- Enclosed Alphanumeric Supplement
- Enclosed Ideographic Supplement
- Miscellaneous Symbols and Pictographs
- Emoticons
- Ornamental Dingbats
- Transport and Map Symbols
- Alchemical Symbols
- Geometric Shapes Extended
- Supplemental Symbols and Pictographs
- CJK Unified Ideographs Extension B
- CJK Unified Ideographs Extension C
- CJK Unified Ideographs Extension D
- CJK Unified Ideographs Extension E
- CJK Compatibility Ideographs Supplement

As of Unicode 9.0 and [revision 16 of UTR #50](http://www.unicode.org/reports/tr50/proposed.html), the following astral-plane blocks have upright vertical orientation:
- Meroitic Hieroglyphs
- Siddham
- Egyptian Hieroglyphs
- Anatolian Hieroglyphs
- Ideographic Symbols and Punctuation
- Tangut
- Tangut Components
- Kana Supplement
- Byzantine Musical Symbols
- Musical Symbols
- Tai Xuan Jing Symbols
- Counting Rod Numerals
- Sutton SignWriting
- Mahjong Tiles
- Domino Tiles
- Playing Cards
- Enclosed Alphanumeric Supplement
- Enclosed Ideographic Supplement
- Miscellaneous Symbols and Pictographs
- Emoticons
- Ornamental Dingbats
- Transport and Map Symbols
- Alchemical Symbols
- Geometric Shapes Extended
- Supplemental Symbols and Pictographs
- CJK Unified Ideographs Extension B
- CJK Unified Ideographs Extension C
- CJK Unified Ideographs Extension D
- CJK Unified Ideographs Extension E
- CJK Compatibility Ideographs Supplement

The following astral-plane blocks have neutral vertical orientation:
- Supplementary Private Use Area-A
- Supplementary Private Use Area-B

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-js/issues/4001
