### ISSUE TITLE
add line-offset style property

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/DEPRECATED-mapbox-gl#3]
- [x] add property to `mapbox-gl-style-spec` ([merged](https://github.com/mapbox/mapbox-gl-style-spec/pull/383) :ship:)
- [x] add tests to `mapbox-gl-test-suite` ([merged](https://github.com/mapbox/mapbox-gl-test-suite/pull/60) :ship:)
- [x] implement property in `mapbox-gl-js` ([merged](https://github.com/mapbox/mapbox-gl-js/pull/1780) :ship:)
- [x] implement property in `mapbox-gl-native` ([merged](https://github.com/mapbox/mapbox-gl-native/pull/3092) :ship:)
- [x] update internal APIs to use latest style spec and GL JS (:ship:)

cc @jfirebaugh @kkaefer

**Comment by kkaefer** [comment]
We should reverse the offset direction to be more intuitive:
- [x] change tests in [`mapbox-gl-test-suite`](https://github.com/mapbox/mapbox-gl-test-suite/pull/66)
- [x] change [`mapbox-gl-native`](https://github.com/mapbox/mapbox-gl-native/issues/3208)
- [x] change [`mapbox-gl-js`](https://github.com/mapbox/mapbox-gl-js/issues/1808)
- [x] change [`mapbox-gl-style-spec`](https://github.com/mapbox/mapbox-gl-style-spec/pull/386)
