### ISSUE TITLE
Building roofs rendering in 3D 

### ISSUE THREAD

**Issue by popovae** [mapbox/DEPRECATED-mapbox-gl#30]
Is there any way to render roof or part of the roof in 3D? Or may be a solution to draw geometry with different height of the points like the one on screenshot bellow?
![2](https://cloud.githubusercontent.com/assets/6538329/20559169/077d4908-b17c-11e6-9dcf-9d0e4fe33f56.png)

**Comment by jfirebaugh** [comment]
Duplicate of #18.
