### ISSUE TITLE
Client-side, data-driven rendering hooks in Mapbox GL JS

### ISSUE THREAD

**Issue by cebartling** [mapbox/DEPRECATED-mapbox-gl#32]
## Motivation

Mapbox GL JS uses raster and vector tilesets as core pieces of making maps visible in the browser and relies heavily on both raster and vector tilesets to keep their maps fast and efficient. Our company will mostly use raster-based tilesets.  Raster tilesets are created when raster images, in TIFF and GeoTIFF format, are uploaded and processed by Mapbox Studio. Our company currently uploads various types of mosaic raster images into Mapbox Studio for creating raster tilesets that can be layered onto maps rendered in the Mapbox GL JS library.  Mapbox itself provides their satellite map imagery as a raster tileset. 

Our company has some more complex requirements where certain raster tilesets will need to be colorized on the _client-side_ using a data-driven approach. This colorization process needs to be performed client-side as the colorization scheme is manipulated by our users in our web UI. Therefore, our developers will need to be able to hook into the rendering pipeline of the Mapbox GL JS library and provide colorization information to the fragment shader used to transform raster image pixel color.

## Design Alternatives

This need for client-side, data-driven rendering hooks has been cited by other customers. Ubilabs wrote a [blog post](https://medium.com/@Scarysize/data-driven-raster-layer-with-mapbox-gl-bdb3b747ae22#.ph3do9v8k) about how they built this feature into a forked version of Mapbox GL JS.  In that writeup, they build a colorization lookup texture in JavaScript that maps values in the range of 0 to 255 to a unique color.  This colorization lookup texture is then passed to a custom fragment shader that transforms each pixel value of an input raster tile to a color mapped by the generated colorization lookup texture.  The input raster tile is grayscale, thus locking all color channels, so only the red channel is used to determine pixel value. Those pixel values can range from 0 to 255. 

This is exactly the solution our company needs for our colorization of mosaic images layered on the map.  The downside of the Ubilabs solution is that they forked Mapbox GL JS to get their solution to work. Our company would like to avoid having to fork the Mapbox GL JS module to get this functionality.

**Comment by lucaswoj** [comment]
Merging with https://github.com/mapbox/mapbox-gl-js/issues/3889
