### ISSUE TITLE
Decide on terminology for map loading states 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/DEPRECATED-mapbox-gl#5]
In https://github.com/mapbox/mapbox-gl-native/pull/3318 and https://github.com/mapbox/mapbox-gl-js/issues/1715 we're trying to come up with the right terminology to describe map loading states. So far, we have identified at least 2 states that need unique descriptive names (but I think there are some more interesting ones)
- everything has loaded for the initial map viewport (presently captured by the `load` event)
- everything has loaded for the current map viewport (presently unnamed)

(NOTE: "everything" = styles, tilejson, tiles, geojson, glyphs, sprites)

**Comment by brunoabinader** [comment]
I vote for `ready` instead of `loaded` because loading a resource does not necessarily indicate that a resource is `ready` for usage e.g. we can say that a style is `ready` after all its sources in which at least one visible layer are loaded, which means not _all_ of its sources needs to be loaded.

**Comment by jfirebaugh** [comment]
> - everything has loaded for the initial map viewport (presently captured by the load event)

Let's leave this event named `load`, for backward compatibility and `window.onload` precedent.

> - everything has loaded for the current map viewport 

I vote for naming the event `quiesce`, and the accessor `isQuiescent()`. It's an uncommon enough word that we can attach our own domain-specific meaning to it.

### qui·es·cent

_adjective_: in a state or period of inactivity.
"After an animation finishes and all tiles have been loaded, the map becomes quiescent and the frame rate drops to zero."

**Comment by tmcw** [comment]
-1 for quiesce, on account of spelling difficulty

**Comment by lucaswoj** [comment]
+1 for quiesce, on account of semantic differentiation from `load` and it being and uncommon enough word that we can attach our own domain-specific meaning to it.
